# 서버 설정
server:
  port: 8080
  servlet:
    context-path:  /
    encoding:
      charset: UTF-8
      
# 뷰 리졸버 설정
spring:
  mvc:
    view:
      prefix: /WEB-INF/health/
      suffix: .jsp
      
# 데이터 소스 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

# JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect # generate 해주는 설정
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update  #create나 update만 쓴다.
      use-new-id-generator-mappings: false
    properties:
      hibernate.format_sql: true